services:
  - type: web
    name: phishing-awareness-simulation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:5000 app.app:app"
    plan: free
